### ISSUE TITLE
[REQUEST][HELP]Getting error`browser` object that is not fully initialised

### ISSUE THREAD

**Issue by EINBOX** [wswebcreation/swiping-your-way-through-appium#2] opened 2021-09-29 16:24 UTC
Sir,
I am requesting you to how can I write helpers method using key browser because am getting the below error
Please provide some samples 

want like in async method
 _tap (from, to) {
        browser.performActions([
            {
            type: 'pointer',
            id: 'finger1',
            parameters: {pointerType: 'touch'},
            actions: [
                {type: 'pointerMove', duration: 2, x: from, y: to},
                {type: 'pointerDown', button: 0},
                {type: 'pause', duration: 10},
                {type: 'pointerUp', button: 0},
            }
        ]);
        driver.pause(1000);
    }_
```
  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
```

Thanks IN Advance

**Comment by wswebcreation** [comment] 2021-09-29 17:47
Not sure what you're doing here, can you give more code so I an help you?

**Comment by EINBOX** [comment] 2021-09-30 03:36
This is the code :

```
class PageHelpers {
    ;async tap() {
        await browser.performActions([
            {
                type: 'pointer',
                id: 'finger1',
                parameters: {pointerType: 'touch'},
                actions: [
                    {type: 'pointerMove', duration: 2, x: 330, y: 200},
                    {type: 'pointerDown', button: 0},
                    {type: 'pause', duration: 10},
                    {type: 'pointerUp', button: 0},
                    {type: 'pointerMove', duration: 2, x: 310, y: 200},
                    {type: 'pointerDown', button: 0},
                    {type: 'pause', duration: 10},
                    {type: 'pointerUp', button: 0}
                ]
            }
        ]);
        await browser.pause(1000);
    }
}
```

**Comment by wswebcreation** [comment] 2021-09-30 05:12
Can you also provide some more context, like the spec file, the error logs and a config. I can't debug it with a reproducible example

**Comment by EINBOX** [comment] 2021-09-30 06:18
```
Logs:
Execution of 1 workers started at 2021-09-30T06:10:37.440Z

2021-09-30T06:10:37.442Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2021-09-30T06:10:37.537Z INFO @wdio/cli:launcher: Run onPrepare hook
<<< BROWSER TESTS STARTED >>>
2021-09-30T06:11:48.241Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 70704ms
2021-09-30T06:11:48.245Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-09-30T06:11:48.245Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-09-30T06:11:48.245Z INFO @wdio/local-runner: Start worker 0-0 with arg: config/wdio.localBrowser.config.js
[0-0] 2021-09-30T06:11:49.171Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-09-30T06:11:49.392Z DEBUG @wdio/config:utils: Found 'ts-node' package, auto-compiling TypeScript files
[0-0] 2021-09-30T06:11:49.398Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-09-30T06:11:49.403Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
[0-0] 2021-09-30T06:11:50.514Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): /Users/<usertest>/Downloads/wdtest/test/specs/example.e2e.js
[0-0] Error: TypeError: Class extends value #<Page> is not a constructor or null
[0-0]     at Object.<anonymous> (/Users/<usertest>/Downloads/wdtest/test/pageobjects/login.page.js:6:25)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[0-0]     at Module._compile (/Users/<usertest>/Downloads/wdtest/node_modules/pirates/lib/index.js:99:24)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[0-0]     at Object.newLoader [as .js] (/Users/<usertest>/Downloads/wdtest/node_modules/pirates/lib/index.js:104:7)
[0-0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0-0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0-0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0-0]     at require (node:internal/modules/cjs/helpers:94:18)
[0-0]     at Object.<anonymous> (/Users/<usertest>/Downloads/wdtest/test/specs/example.e2e.js:3:19)
[0-0] RUNNING in chrome - /test/specs/example.e2e.js
[0-0] 2021-09-30T06:11:50.665Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-09-30T06:11:50.666Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-09-30T06:11:50.671Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session
[0-0] 2021-09-30T06:11:50.671Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: { browserName: 'chrome', 'goog:chromeOptions': {} },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: { browserName: 'chrome', 'goog:chromeOptions': {} }
[0-0] }
[0-0] 2021-09-30T06:11:53.087Z INFO webdriver: COMMAND navigateTo("https://web-reader.azurewebsites.net/")
[0-0] 2021-09-30T06:11:53.087Z INFO webdriver: [POST] http://localhost:4444/wd/hub/session/f3b9d1dc80656c3d2bf8adefa6e7813b/url
[0-0] 2021-09-30T06:11:53.088Z INFO webdriver: DATA { url: 'https://web-reader.azurewebsites.net/' }
[0-0] <<< BROWSER TESTS STARTED >>>https://web-reader.azurewebsites.net/
[0-0] 2021-09-30T06:11:58.635Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 5549ms
[0-0] 2021-09-30T06:11:58.638Z ERROR @wdio/runner: Error: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`.
[0-0] Helper files that use other `browser` commands have to be moved to `before` hook.
[0-0] Spec file(s): /Users/<usertest>/Downloads/wdtest/test/specs/example.e2e.js
[0-0] Error: TypeError: Class extends value #<Page> is not a constructor or null
[0-0]     at Object.<anonymous> (/Users/<usertest>/Downloads/wdtest/test/pageobjects/login.page.js:6:25)
[0-0]     at Module._compile (node:internal/modules/cjs/loader:1101:14)
[0-0]     at Module._compile (/Users/<usertest>/Downloads/wdtest/node_modules/pirates/lib/index.js:99:24)
[0-0]     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
[0-0]     at Object.newLoader [as .js] (/Users/<usertest>/Downloads/wdtest/node_modules/pirates/lib/index.js:104:7)
[0-0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0-0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0-0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0-0]     at require (node:internal/modules/cjs/helpers:94:18)
[0-0]     at Object.<anonymous> (/Users/<usertest>/Downloads/wdtest/test/specs/example.e2e.js:3:19)
[0-0]     at MochaAdapter._loadFiles (/Users/<usertest>/Downloads/wdtest/node_modules/@wdio/mocha-framework/build/index.js:85:35)
[0-0]     at MochaAdapter.init (/Users/<usertest>/Downloads/wdtest/node_modules/@wdio/mocha-framework/build/index.js:54:9)
[0-0]     at Object.adapterFactory.init (/Users/<usertest>/Downloads/wdtest/node_modules/@wdio/mocha-framework/build/index.js:313:22)
[0-0]     at Runner.run (/Users/<usertest>/Downloads/wdtest/node_modules/@wdio/runner/build/index.js:82:27)
[0-0]  Error:  Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
`browser` object has only `capabilities` and some flags like `isMobile`.
Helper files that use other `browser` commands have to be moved to `before` hook.
Spec file(s): /Users/<usertest>/Downloads/wdtest/test/specs/example.e2e.js
Error: TypeError: Class extends value #<Page> is not a constructor or null
    at Object.<anonymous> (/Users/<usertest>/Downloads/wdtest/test/pageobjects/login.page.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (/Users/<usertest>/Downloads/wdtest/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.newLoader [as .js] (/Users/<usertest>/Downloads/wdtest/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/<usertest>/Downloads/wdtest/test/specs/example.e2e.js:3:19)
[0-0] 2021-09-30T06:11:58.640Z INFO webdriver: COMMAND deleteSession()
[0-0] 2021-09-30T06:11:58.641Z INFO webdriver: [DELETE] http://localhost:4444/wd/hub/session/f3b9d1dc80656c3d2bf8adefa6e7813b
2021-09-30T06:11:58.830Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - /test/specs/example.e2e.js
2021-09-30T06:11:58.832Z INFO @wdio/cli:launcher: Run onComplete hook
2021-09-30T06:11:58.832Z INFO @wdio/selenium-standalone-service: shutting down all browsers
2021-09-30T06:11:58.832Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms
<<< TESTING FINISHED >>>

Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:01:21 

2021-09-30T06:11:58.834Z INFO @wdio/local-runner: Shutting down spawned worker
2021-09-30T06:11:59.090Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2021-09-30T06:11:59.090Z INFO @wdio/local-runner: shutting down

```
test.spec
```
const LoginPage = require('../pageobjects/login.page');
const SecurePage = require('../pageobjects/secure.page');
const PageHelpers = require('../helpers/PageHelpers');

//import Gestures from '../helpers/Gestures';
//import { remote, Browser } from "webdriverio";
//import { config } from "../wdio.localBrowser.config";

//let browser: Browser<"async">;

/**before(async () => {
    browser = await remote(config);
});

after(async () => {
    await browser.deleteSession();
});*/


describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();

        await LoginPage.login('tomsmith', 'SuperSecretPassword!');
        await expect(SecurePage.flashAlert).toBeExisting();
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!');
    });

    it('should login with valid credentials', async () => {
        console.log("testing 2nd test case")
        await PageHelpers.tap()
    });
    it('should login with valid credentials', async () => {
        console.log("testing 3rd test case")
    });
});

```

**Comment by wswebcreation** [comment] 2021-09-30 08:00
@EINBOX 

The error is in the logs

` Error: TypeError: Class extends value #<Page> is not a constructor or null`, can you please check your code for errors?

Closing it for now because it's not an issue, but open for further conversation

**Closed as completed by wswebcreation** 2021-09-30 08:00 UTC
